# Site settings
title: "Rivendell - JW's blog"
description: > 
  「说出口的话，离弦的箭，逝去的生活和失去的机会。」
#《商人和炼金术士之门》

author: icarus 507
email: jianwei_feng@foxmail.com

baseurl: "" # the subpath of your site, e.g. /blog 注释掉：/paper-jekyll-theme
url: "" # the base hostname & protocol for your site 注释掉：https://deadbeef.me

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

